### ISSUE TITLE
[FEATURE] Add more population-based nature-inspired algorithms

### ISSUE THREAD

**Issue by firefly-cpp** [rodrigo-arenas/Sklearn-genetic-opt#100]
Thanks for working on this exciting project! Is there a possibility to add more population-based nature-inspired algorithms to your framework?

Is there a possibility to call algorithm implementations from the NiaPy framework?

**Comment by rodrigo-arenas** [comment]
Hi @firefly-cpp, thanks for your message!
At this moment, the package heavily relies on how DEAP structure the evolutionary algorithms, so at this point, it's possible to add more algorithms (there are already three variants), but only the ones that are compatible with DEAP

I've thought as well allowing other "backends" like NiaPy to use different algorithms from different frameworks, this would probably be version 1.0.0 of the package since it would require to re-write probably more than 70% of the package; at this point, I'm not really working on this 1.0.0 version, since it'd be worth it if the package gains more users/contributors to make it possible

I hope it makes sense, greetings

**Comment by firefly-cpp** [comment]
Thanks for your explanation.
