### ISSUE TITLE
Out of bounds fitness value 

### ISSUE THREAD

**Issue by lorenzodelmedico** [rodrigo-arenas/Sklearn-genetic-opt#118]
Hello, 

I'm using GA Feature Selection Class for Feature Selection on a professional project. Depending on generation, logbook returns me values that i have a hard time explaining (see capture below, on generation 3, 16, 18, 19 here). 

<img width="439" alt="fitness_incoherent_values" src="https://user-images.githubusercontent.com/50697087/216302670-dbe4d3d4-87f3-4a67-9fe5-0cd5dd5ec193.png">

The algorithm parameters are shown below : 

<img width="573" alt="parameter_genetic" src="https://user-images.githubusercontent.com/50697087/216304799-0b63c113-f0aa-43eb-a65a-53c8f5fbc30e.png">

I've been looking in the doc, code and also on Deap Github (i don't know yet if it's related to this implementation or it comes from Deap), i can't find a satisfying answer for this matter. I have identified so far that depending on crossover and mutation value it happens more or less often, and i think that there is some multiplication with weighted values that may explain this value. My understanding is that it's a penalization that occurs for some reason during fitness evaluation. I want to know exactly why it happens, and that's why i'm opening this issue, i hope someone can give me a hint, if i find it by myself in the meanwhile i'll update my issue.

**Comment by rodrigo-arenas** [comment]
Hi @lorenzodelmedico 
This happens because **some** of the solutions found in that generation have either 0 features selected or a number higher than the parameter `max_features`, in this case, the package will apply a penalization term on the objective function to let know the GA algorithm that such solution is unwanted.
Notice that even if you got some solutions that look like this, not all of them are penalized and are valid solutions, you can check that for instance the max score of generation 19 is 0.715424, and that one is going to be selected as the best solution found

I hope this explanation makes it more clear, let me know if you have more questions

**Comment by rodrigo-arenas** [comment]
I'm closing this issue, let me know if something else related to this raises
