### ISSUE TITLE
Modify the params of the GASearchCV

### ISSUE THREAD

**Issue by JuanCamilo-R** [rodrigo-arenas/Sklearn-genetic-opt#145]
Is there any way I can modify the params of the GASearchCV such as population_size, crossover_population, etc... on each generation with a callback?

**Comment by rodrigo-arenas** [comment]
Hi @JuanCamilo-R 
Theoretically, you could modify some of those properties, the callbacks take as argument the whole GASearchCV object so that it could be modified, but depending on what you change It may break, so be careful
Check for example: https://sklearn-genetic-opt.readthedocs.io/en/stable/tutorials/custom_callback.html

For the mutation and crossover probability, there is already a safe way to do it through adapters (you could also define custom adapters), you can check it here:

https://sklearn-genetic-opt.readthedocs.io/en/stable/tutorials/adapters.html

**Comment by JuanCamilo-R** [comment]
I will definitely take a deeper look into adapters. However, in terms of the 'custom callback' approach, when you mention that it takes as argument the whole GASearchCV object, do you mean the 'self' argument in the functions: 'on_step', 'on_start' and 'on_end'? 
Thank you for your response :)

**Comment by rodrigo-arenas** [comment]
There is one parameter called estimator on those functions which is the GASearchCV class, from there you could access its properties
Let me know if you have further questions
